"""Constants for the Tribal Village environment."""

# Observation space bounds
OBS_MIN_VALUE = 0
OBS_MAX_VALUE = 255
OBS_NORMALIZATION_FACTOR = 1.0 / OBS_MAX_VALUE

# Environment defaults
DEFAULT_MAX_STEPS = 10_000
DEFAULT_RENDER_SCALE = 4
DEFAULT_ANSI_BUFFER_SIZE = 1_000_000

# CLI defaults
DEFAULT_ANSI_STEPS = 128
DEFAULT_PROFILE_STEPS = 512

# Training defaults
DEFAULT_TRAIN_MAX_STEPS = 1_000
DEFAULT_NUM_ENVS = 64
DEFAULT_CHECKPOINT_INTERVAL = 200

# PPO hyperparameters
DEFAULT_LEARNING_RATE = 0.0005
DEFAULT_BPTT_HORIZON = 64
DEFAULT_ADAM_EPS = 1e-8
DEFAULT_GAMMA = 0.995
DEFAULT_GAE_LAMBDA = 0.90
DEFAULT_UPDATE_EPOCHS = 1
DEFAULT_CLIP_COEF = 0.2
DEFAULT_VF_COEF = 2.0
DEFAULT_VF_CLIP_COEF = 0.2
DEFAULT_MAX_GRAD_NORM = 1.5
DEFAULT_ENT_COEF = 0.01
DEFAULT_ADAM_BETA1 = 0.95
DEFAULT_ADAM_BETA2 = 0.999
DEFAULT_MAX_MINIBATCH_SIZE = 32768
DEFAULT_VTRACE_RHO_CLIP = 1.0
DEFAULT_VTRACE_C_CLIP = 1.0
DEFAULT_PRIO_ALPHA = 0.8
DEFAULT_PRIO_BETA0 = 0.2

# Policy defaults
DEFAULT_HIDDEN_SIZE = 256
