# This file is included by ai_policies_default.nim
include "ai_role_hearter"
include "ai_role_armorer"
include "ai_role_hunter"
include "ai_role_baker"
include "ai_role_lighter"
include "ai_role_farmer"
include "ai_role_builder"
include "ai_role_miner"
include "ai_role_smelter"
include "ai_role_guard"
include "ai_role_medic"
include "ai_role_scout"
include "ai_role_carpenter"
include "ai_role_mason"
include "ai_role_brewer"
