# This file is included by ai_policies_default.nim
include "hearter"
include "armorer"
include "hunter"
include "baker"
include "lighter"
include "farmer"
include "builder"
include "miner"
include "smelter"
include "guard"
include "medic"
include "scout"
include "carpenter"
include "mason"
include "brewer"
