# This file is included by defaults.nim
include "hearter"
include "armorer"
include "hunter"
include "baker"
include "lighter"
include "farmer"
include "builder"
include "miner"
include "guard"
include "medic"
include "scout"
